version: "3.1"
services:

    mysql:
      image: mysql:8.0.1
      container_name: gfg-mysql
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/mysql/data:/var/lib/mysql
        - ./phpdocker/mysql/gfg_products.sql:/docker-entrypoint-initdb.d/dump.sql
        - ./phpdocker/mysql/conf.d:/etc/mysql/conf.d/
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=gfg
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password
      ports:
        - "3306:3306"

    webserver:
      image: nginx:alpine
      container_name: gfg-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: gfg-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      #TODO maybe move into php Dockerfile
      command: /bin/sh -c "cd /application/gfg-api/ && composer install && composer dump-autoload -o && /usr/bin/php-fpm"
